//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resourceTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("resourceTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StPr_
        ///udf.
        /// </summary>
        internal static string alter {
            get {
                return ResourceManager.GetString("alter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if exists (select * from dbo.sysobjects where id = object_id(N&apos;[dbo].[StPr_InsertEntoliApokin]&apos;) and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1)
        ///drop procedure [dbo].[StPr_InsertEntoliApokin]
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER OFF
        ///GO
        ///SET ANSI_NULLS OFF
        ///GO
        ///
        ///-- INSERT STORED PROCEDURE HERE
        ///
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///.
        /// </summary>
        internal static string StPr_ {
            get {
                return ResourceManager.GetString("StPr_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET QUOTED_IDENTIFIER OFF
        ///GO
        ///SET ANSI_NULLS OFF
        ///GO
        ///
        ///if exists (select * from dbo.sysobjects where id = object_id(N&apos;[dbo].[XXXXXXXXXX]&apos;) and xtype in (N&apos;FN&apos;, N&apos;IF&apos;, N&apos;TF&apos;))
        ///drop function [dbo].[XXXXXXXXXX]
        ///GO
        ///
        ///-- INSERT UDF HERE
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string udf {
            get {
                return ResourceManager.GetString("udf", resourceCulture);
            }
        }
    }
}
